import feedImage from "@/assets/feed-1.png";

const postsData = [
  {
    id: 1,
    name: "Md. Emon",
    title: "General Manager at Ha-Meem Group",
    time: "1 hr.",
    type: "job-post",
    badgeColor: "bg-blue-100 text-blue-800",
    content:
      "FabricPro industries is seeking a skilled Textile Process Engineer to optimize production processes and ensure quality control in dyeing.",
    image: feedImage,
    likedBy: "Benjir",
    likesCount: 23,
  },
  {
    id: 2,
    name: "Sadia Noor",
    title: "Intern at Square Textiles",
    time: "2 hr.",
    type: "internship",
    badgeColor: "bg-green-100 text-green-800",
    content:
      "We are hiring passionate interns to work on spinning and dyeing production line. Apply now and grow with us!",
    image: feedImage,
    likedBy: "Sami",
    likesCount: 15,
  },
  {
    id: 3,
    name: "Rafiul Hasan",
    title: "Senior Officer at Beximco",
    time: "4 hr.",
    type: "success-stories",
    badgeColor: "bg-purple-100 text-purple-800",
    content:
      "I joined Beximco 2 years ago. Here's my journey from trainee to senior officer in finishing department.",
    image: feedImage,
    likedBy: "Jannat",
    likesCount: 42,
  },
  {
    id: 4,
    name: "Tanjina Akter",
    title: "Product Developer at DBL Group",
    time: "3 hr.",
    type: "job-post",
    badgeColor: "bg-blue-100 text-blue-800",
    content:
      "Looking for experienced knitwear designers to join our innovation lab at DBL Group.",
    image: feedImage,
    likedBy: "Rakib",
    likesCount: 34,
  },
  {
    id: 5,
    name: "Hasib Mahmud",
    title: "Lecturer at BUTEX",
    time: "5 hr.",
    type: "success-stories",
    badgeColor: "bg-purple-100 text-purple-800",
    content:
      "Proud to share that three of my students are now working in top denim mills. Keep inspiring!",
    image: feedImage,
    likedBy: "Sumaiya",
    likesCount: 20,
  },
  {
    id: 6,
    name: "Farzana Hossain",
    title: "HR Executive at Fakir Apparels",
    time: "30 min.",
    type: "job-post",
    badgeColor: "bg-blue-100 text-blue-800",
    content:
      "Urgently hiring for a Merchandiser (Woven). Must have 2+ years of experience with buyer handling.",
    image: feedImage,
    likedBy: "Nafi",
    likesCount: 18,
  },
  {
    id: 7,
    name: "Arafat Himu",
    title: "Intern at Ananta Group",
    time: "45 min.",
    type: "internship",
    badgeColor: "bg-green-100 text-green-800",
    content:
      "My internship journey at Ananta Group has been full of learning! Hoping to convert to full-time soon.",
    image: feedImage,
    likedBy: "Tisha",
    likesCount: 10,
  },
  {
    id: 8,
    name: "Nusrat Jahan",
    title: "Fabric QC at Viyellatex",
    time: "6 hr.",
    type: "success-stories",
    badgeColor: "bg-purple-100 text-purple-800",
    content:
      "Moved from R&D to QC in 6 months! Thanks to my mentors at Viyellatex for believing in me.",
    image: feedImage,
    likedBy: "Fahim",
    likesCount: 29,
  },
  {
    id: 9,
    name: "Kamrul Islam",
    title: "Dyeing Manager at Envoy Textiles",
    time: "7 hr.",
    type: "job-post",
    badgeColor: "bg-blue-100 text-blue-800",
    content:
      "Hiring Assistant Dyeing Manager – Indigo. Must have denim experience. Apply via our portal.",
    image: feedImage,
    likedBy: "Asif",
    likesCount: 37,
  },
  {
    id: 10,
    name: "Rumana Aktar",
    title: "Student at BUTEX",
    time: "8 hr.",
    type: "internship",
    badgeColor: "bg-green-100 text-green-800",
    content:
      "Completed a two-month internship at Pakiza Knit Composite Ltd. Best learning experience ever!",
    image: feedImage,
    likedBy: "Sakib",
    likesCount: 22,
  },
  {
    id: 11,
    name: "Mohammad Ashik",
    title: "Lab Assistant at Thermax",
    time: "9 hr.",
    type: "job-post",
    badgeColor: "bg-blue-100 text-blue-800",
    content:
      "We need a chemical engineer with textile background for our effluent treatment plant. Immediate joiners preferred!",
    image: feedImage,
    likedBy: "Jubair",
    likesCount: 14,
  },
  {
    id: 12,
    name: "Shakila Rahman",
    title: "Apparel Designer at Epyllion",
    time: "10 hr.",
    type: "success-stories",
    badgeColor: "bg-purple-100 text-purple-800",
    content:
      "My latest collection launched this week! So grateful to be working with an amazing team at Epyllion.",
    image: feedImage,
    likedBy: "Tamim",
    likesCount: 45,
  },
];

export default postsData;
