"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
import { Footer } from "@/components/ui/footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentPath = usePathname();
  const isDashboard =
    currentPath.startsWith("/overview") ||
    currentPath.startsWith("/students") ||
    currentPath.startsWith("/alumni") ||
    currentPath.startsWith("/jobs/feed") ||
    currentPath.startsWith("/jobs/manage") ||
    currentPath.startsWith("/team") ||
    currentPath.startsWith("/settings") ||
    currentPath.startsWith("/profile");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isDashboard ? (
          children
        ) : (
          <div>
            <Navbar />
            {children}
            <Footer />
          </div>
        )}
      </body>
    </html>
  );
}
