import { StudentDataTable } from "@/components/student-data-table";
import profileImage from "@/assets/profile.png";

const students = [
  {
    id: "22090101029",
    name: "Md. Jubayer Sarker",
    profileImage: profileImage.src,
    batch: "4th Batch",
    department: "YE",
    job: "Software Engineer",
    district: "Rangpur",
    contact: "123-456-7890",
  },
  {
    id: "2209010102",
    name: "Jane Smith",
    profileImage: profileImage.src,
    batch: "Batch B",
    department: "HR",
    job: "Manager",
    district: "Los Angeles",
    contact: "987-654-3210",
  },
  {
    id: "2209010103",
    name: "Alice Johnson",
    profileImage: profileImage.src,
    batch: "Batch C",
    department: "Finance",
    job: "Analyst",
    district: "Chicago",
    contact: "555-123-4567",
  },
  {
    id: "2209010104",
    name: "Bob Brown",
    profileImage: profileImage.src,
    batch: "Batch D",
    department: "Marketing",
    job: "Designer",
    district: "Houston",
    contact: "444-987-6543",
  },
  {
    id: "2209010105",
    name: "Charlie Green",
    profileImage: profileImage.src,
    batch: "Batch E",
    department: "IT",
    job: "Developer",
    district: "Phoenix",
    contact: "333-555-7890",
  },
  {
    id: "2209010106",
    name: "Diana White",
    profileImage: profileImage.src,
    batch: "Batch F",
    department: "Sales",
    job: "Sales Rep",
    district: "Philadelphia",
    contact: "222-666-1234",
  },
  {
    id: "2209010107",
    name: "Ethan Black",
    profileImage: profileImage.src,
    batch: "Batch G",
    department: "Support",
    job: "Support Specialist",
    district: "San Antonio",
    contact: "111-777-8901",
  },
  {
    id: "2209010108",
    name: "Fiona Blue",
    profileImage: profileImage.src,
    batch: "Batch H",
    department: "Operations",
    job: "Operations Manager",
    district: "Dallas",
    contact: "888-999-1234",
  },
  {
    id: "2209010109",
    name: "George Grey",
    profileImage: profileImage.src,
    batch: "Batch I",
    department: "Legal",
    job: "Lawyer",
    district: "San Diego",
    contact: "777-888-4567",
  },
  {
    id: "2209010110",
    name: "Hannah Yellow",
    profileImage: profileImage.src,
    batch: "Batch J",
    department: "Research",
    job: "Researcher",
    district: "San Jose",
    contact: "666-555-7890",
  },
  {
    id: "2209010111",
    name: "Ian Red",
    profileImage: profileImage.src,
    batch: "Batch K",
    department: "Engineering",
    job: "Mechanical Engineer",
    district: "Austin",
    contact: "123-123-1234",
  },
  {
    id: "2209010112",
    name: "Jenny Purple",
    profileImage: profileImage.src,
    batch: "Batch L",
    department: "Admin",
    job: "Admin Officer",
    district: "Jacksonville",
    contact: "321-321-4321",
  },
  {
    id: "2209010113",
    name: "Kevin Gold",
    profileImage: profileImage.src,
    batch: "Batch M",
    department: "Security",
    job: "Security Analyst",
    district: "Fort Worth",
    contact: "999-888-7777",
  },
  {
    id: "2209010114",
    name: "Linda Silver",
    profileImage: profileImage.src,
    batch: "Batch N",
    department: "Creative",
    job: "Art Director",
    district: "Columbus",
    contact: "987-123-6543",
  },
  {
    id: "2209010115",
    name: "Mark Bronze",
    profileImage: profileImage.src,
    batch: "Batch O",
    department: "Logistics",
    job: "Supply Manager",
    district: "Charlotte",
    contact: "567-432-1098",
  },
  {
    id: "2209010116",
    name: "Nina Aqua",
    profileImage: profileImage.src,
    batch: "Batch P",
    department: "Architecture",
    job: "Architect",
    district: "San Francisco",
    contact: "654-321-0987",
  },
  {
    id: "2209010117",
    name: "Oscar Mint",
    profileImage: profileImage.src,
    batch: "Batch Q",
    department: "Health",
    job: "Doctor",
    district: "Indianapolis",
    contact: "765-555-1234",
  },
  {
    id: "2209010118",
    name: "Paula Rose",
    profileImage: profileImage.src,
    batch: "Batch R",
    department: "Education",
    job: "Teacher",
    district: "Seattle",
    contact: "456-678-2345",
  },
  {
    id: "2209010119",
    name: "Quentin Flame",
    profileImage: profileImage.src,
    batch: "Batch S",
    department: "Science",
    job: "Chemist",
    district: "Denver",
    contact: "567-876-3456",
  },
  {
    id: "2209010120",
    name: "Rachel Snow",
    profileImage: profileImage.src,
    batch: "Batch T",
    department: "Media",
    job: "Journalist",
    district: "Washington",
    contact: "678-543-8765",
  },
  {
    id: "2209010121",
    name: "Sam Rain",
    profileImage: profileImage.src,
    batch: "Batch U",
    department: "Law",
    job: "Judge",
    district: "Boston",
    contact: "789-345-0987",
  },
  {
    id: "2209010122",
    name: "Tina Storm",
    profileImage: profileImage.src,
    batch: "Batch V",
    department: "Aviation",
    job: "Pilot",
    district: "El Paso",
    contact: "890-234-5678",
  },
  {
    id: "2209010123",
    name: "Umar Light",
    profileImage: profileImage.src,
    batch: "Batch W",
    department: "Transportation",
    job: "Driver",
    district: "Nashville",
    contact: "345-678-9012",
  },
  {
    id: "2209010124",
    name: "Vera Dark",
    profileImage: profileImage.src,
    batch: "Batch X",
    department: "Design",
    job: "UX Designer",
    district: "Detroit",
    contact: "234-890-6789",
  },
  {
    id: "2209010125",
    name: "Will Green",
    profileImage: profileImage.src,
    batch: "Batch Y",
    department: "AI",
    job: "ML Engineer",
    district: "Memphis",
    contact: "987-432-1098",
  },
  {
    id: "2209010126",
    name: "Xena Nova",
    profileImage: profileImage.src,
    batch: "Batch Z",
    department: "Biotech",
    job: "Biologist",
    district: "Portland",
    contact: "123-098-5678",
  },
  {
    id: "2209010127",
    name: "Yusuf Stone",
    profileImage: profileImage.src,
    batch: "Batch AA",
    department: "Geology",
    job: "Geologist",
    district: "Oklahoma City",
    contact: "890-123-4567",
  },
  {
    id: "2209010128",
    name: "Zara Sky",
    profileImage: profileImage.src,
    batch: "Batch AB",
    department: "Astronomy",
    job: "Astronomer",
    district: "Las Vegas",
    contact: "876-543-2109",
  },
];

const StudentsPage = () => {
  return (
    <div className="mx-8">
      <StudentDataTable students={students} />
    </div>
  );
};

export default StudentsPage;
